package com.jmat.powertools.modules.conversions

const val CONVERSIONS_ACTION_KEY = "CONVERSIONS_ACTION_KEY"
const val CONVERSIONS_ACTION_KM_TO_MILES = "CONVERSIONS_ACTION_KM_TO_MILES"
const val CONVERSIONS_ACTION_KM_TO_MPG = "CONVERSIONS_ACTION_KM_TO_MPG"
const val CONVERSIONS_ACTION_MILLILITERS_TO_OUNCES = "CONVERSIONS_ACTION_MILLILITERS_TO_OUNCES"